const availableTeams = [
  {
    id: 1,
    name: "Hà Nội FC",
    city: "Hà Nội",
    coach: "Gad",
    stadium: "Hàng Đẫy",
    stadiumId: 1,
    capacity: 22500,
    standard: 5,
    home_kit_image: "https://upload.wikimedia.org/wikipedia/vi/e/eb/Hanoi_FC.png",
    away_kit_image: null,
    third_kit_image: null,
    description: "Câu lạc bộ bóng đá Hà Nội",
    season: null,
  },
  {
    id: 2,
    name: "Viettel FC",
    city: "Hà Nội",
    coach: "Tăng Nhất",
    stadium: "Hàng Đẫy",
    stadiumId: 1,
    capacity: 22500,
    standard: 4,
    home_kit_image: null,
    away_kit_image:
      "https://upload.wikimedia.org/wikipedia/vi/thumb/d/d5/Viettel_FC_logo.png/1200px-Viettel_FC_logo.png",
    third_kit_image: null,
    description: "Câu lạc bộ bóng đá Viettel",
    season: null,
  },
  {
    id: 3,
    name: "SHB Đà Nẵng",
    city: "Đà Nẵng",
    coach: "Lê Huỳnh Đức",
    stadium: "Hòa Xuân",
    stadiumId: 3,
    capacity: 20000,
    standard: 3,
    home_kit_image: "https://upload.wikimedia.org/wikipedia/vi/thumb/8/88/SHB_Da_Nang_FC_logo.svg/1200px-SHB_Da_Nang_FC_logo.svg.png",
    away_kit_image: "https://example.com/shb_danang_away.png",
    third_kit_image: null,
    description: "Câu lạc bộ bóng đá SHB Đà Nẵng",
    season: null,
  },
  {
    id: 4,
    name: "Becamex Bình Dương",
    city: "Thủ Dầu Một",
    coach: "Nguyễn Thanh Sơn",
    stadium: "Gò Đậu",
    stadiumId: 4,
    capacity: 18250,
    standard: 4,
    home_kit_image: "https://upload.wikimedia.org/wikipedia/vi/thumb/7/72/Becamex_Binh_Duong_FC_logo.svg/1200px-Becamex_Binh_Duong_FC_logo.svg.png",
    away_kit_image: null,
    third_kit_image: "https://example.com/binhduong_third.png",
    description: "Câu lạc bộ bóng đá Becamex Bình Dương",
    season: null,
  },
  {
    id: 5,
    name: "Hải Phòng FC",
    city: "Hải Phòng",
    coach: "Chu Đình Nghiêm",
    stadium: "Lạch Tray",
    stadiumId: 5,
    capacity: 28000,
    standard: 4,
    home_kit_image: "https://upload.wikimedia.org/wikipedia/vi/thumb/c/c3/Hai_Phong_FC_logo.svg/1200px-Hai_Phong_FC_logo.svg.png",
    away_kit_image: null,
    third_kit_image: null,
    description: "Câu lạc bộ bóng đá Hải Phòng",
    season: null,
  },
  {
    id: 6,
    name: "Nam Định FC",
    city: "Nam Định",
    coach: "Vũ Hồng Việt",
    stadium: "Thiên Trường",
    stadiumId: 6,
    capacity: 20000,
    standard: 3,
    home_kit_image: "https://upload.wikimedia.org/wikipedia/vi/thumb/b/b8/Nam_%C4%90%E1%BB%8Bnh_FC_logo.png/800px-Nam_%C4%90%E1%BB%8Bnh_FC_logo.png",
    away_kit_image: "https://example.com/namdinh_away.png",
    third_kit_image: null,
    description: "Câu lạc bộ bóng đá Nam Định",
    season: null,
  },
];

const seasons = [
  {
    id: "2023-2024",
    name: "Mùa giải 2023-2024",
    startDate: "2023-08-01",
    endDate: "2024-05-30",
    teams: [1, 2, 3, 4],
    rounds: [
      {
        roundId: "2023-2024-ROUND1",
        name: "Lượt đi",
        startDate: "2023-08-05",
        endDate: "2023-08-07",
      },
      {
        roundId: "2023-2024-ROUND2",
        name: "Lượt về",
        startDate: "2024-01-01",
        endDate: "2024-01-03",
      },
    ],
  },
  {
    id: "2024-2025",
    name: "Mùa giải 2024-2025",
    startDate: "2024-09-01",
    endDate: "2025-06-30",
    teams: [1, 2, 3, 4, 5, 6],
    rounds: [
      {
        roundId: "2024-2025-ROUND1",
        name: "Giai đoạn 1",
        startDate: "2024-09-05",
        endDate: "2024-12-20",
      },
      {
        roundId: "2024-2025-ROUND2",
        name: "Giai đoạn 2",
        startDate: "2025-02-15",
        endDate: "2025-05-30",
      },
    ],
  },
];

const players = {
  "2023-2024": {
    1: [
      {
        id: 1,
        name: "Cầu thủ A1",
        dob: "1999-03-15",
        position: "Tiền đạo",
        nationality: "Việt Nam",
        birthplace: "Hà Nội",
        height: 180,
        weight: 75,
        bio: "Một tiền đạo tài năng của đội.",
        season: "2023-2024",
        playerType: "Trong nước",
      },
      {
        id: 2,
        name: "Văn Quyết",
        dob: "1991-07-01",
        position: "Tiền đạo",
        nationality: "Việt Nam",
        birthplace: "Hà Nội",
        height: 175,
        weight: 70,
        bio: "Đội trưởng tài ba của Hà Nội FC.",
        season: "2023-2024",
        playerType: "Trong nước",
      },
      {
        id: 5,
        name: "Đỗ Hùng Dũng",
        dob: "1993-09-08",
        position: "Tiền vệ",
        nationality: "Việt Nam",
        birthplace: "Hà Nội",
        height: 176,
        weight: 72,
        bio: "Tiền vệ trung tâm xuất sắc.",
        season: "2023-2024",
        playerType: "Trong nước",
      },
    ],
    2: [
      {
        id: 3,
        name: "Cầu thủ B1",
        dob: "1998-05-20",
        position: "Tiền vệ",
        nationality: "Việt Nam",
        birthplace: "Hà Tĩnh",
        height: 178,
        weight: 72,
        bio: "Một tiền vệ năng động của đội.",
        season: "2023-2024",
        playerType: "Trong nước",
      },
      {
        id: 4,
        name: "Hoàng Đức",
        dob: "1998-01-11",
        position: "Tiền vệ",
        nationality: "Việt Nam",
        birthplace: "Hải Dương",
        height: 183,
        weight: 74,
        bio: "Tiền vệ xuất sắc của Viettel FC.",
        season: "2023-2024",
        playerType: "Trong nước",
      },
      {
        id: 6,
        name: "Geovane Magno",
        dob: "1994-03-02",
        position: "Tiền đạo",
        nationality: "Brazil",
        birthplace: "João Pessoa",
        height: 177,
        weight: 78,
        bio: "Tiền đạo ngoại binh chất lượng.",
        season: "2023-2024",
        playerType: "Nước ngoài",
      },
    ],
    3: [
      {
        id: 7,
        name: "Hà Đức Chinh",
        dob: "1997-09-22",
        position: "Tiền đạo",
        nationality: "Việt Nam",
        birthplace: "Phú Thọ",
        height: 176,
        weight: 73,
        bio: "Tiền đạo chủ lực của SHB Đà Nẵng.",
        season: "2023-2024",
        playerType: "Trong nước",
      },
      {
        id: 8,
        name: "Nguyễn Phi Hoàng",
        dob: "2003-03-16",
        position: "Tiền vệ",
        nationality: "Việt Nam",
        birthplace: "Đà Nẵng",
        height: 170,
        weight: 65,
        bio: "Tài năng trẻ đầy triển vọng.",
        season: "2023-2024",
        playerType: "Trong nước",
      },
    ],
    4: [
      {
        id: 9,
        name: "Nguyễn Tiến Linh",
        dob: "1997-10-20",
        position: "Tiền đạo",
        nationality: "Việt Nam",
        birthplace: "Hải Dương",
        height: 183,
        weight: 78,
        bio: "Tiền đạo ngôi sao của Becamex Bình Dương.",
        season: "2023-2024",
        playerType: "Trong nước",
      },
      {
        id: 10,
        name: "Victor Mansaray",
        dob: "1997-01-22",
        position: "Tiền đạo",
        nationality: "Sierra Leone",
        birthplace: "Freetown",
        height: 185,
        weight: 80,
        bio: "Tiền đạo ngoại binh mạnh mẽ.",
        season: "2023-2024",
        playerType: "Nước ngoài",
      },
    ],
  },
  "2024-2025": {
    1: [
      {
        id: 1,
        name: "Cầu thủ A1",
        dob: "1999-03-15",
        position: "Tiền đạo",
        nationality: "Việt Nam",
        birthplace: "Hà Nội",
        height: 180,
        weight: 75,
        bio: "Một tiền đạo tài năng của đội.",
        season: "2024-2025",
        playerType: "Trong nước",
      },
      {
        id: 2,
        name: "Văn Quyết",
        dob: "1991-07-01",
        position: "Tiền đạo",
        nationality: "Việt Nam",
        birthplace: "Hà Nội",
        height: 175,
        weight: 70,
        bio: "Đội trưởng tài ba của Hà Nội FC.",
        season: "2024-2025",
        playerType: "Trong nước",
      },
      {
        id: 5,
        name: "Đỗ Hùng Dũng",
        dob: "1993-09-08",
        position: "Tiền vệ",
        nationality: "Việt Nam",
        birthplace: "Hà Nội",
        height: 176,
        weight: 72,
        bio: "Tiền vệ trung tâm xuất sắc.",
        season: "2024-2025",
        playerType: "Trong nước",
      },
      {
        id: 11,
        name: "Cầu thủ A2",
        dob: "2000-11-20",
        position: "Hậu vệ",
        nationality: "Việt Nam",
        birthplace: "Thái Bình",
        height: 179,
        weight: 74,
        bio: "Hậu vệ cánh đầy tốc độ.",
        season: "2024-2025",
        playerType: "Trong nước",
      },
    ],
    2: [
      {
        id: 3,
        name: "Cầu thủ B1",
        dob: "1998-05-20",
        position: "Tiền vệ",
        nationality: "Việt Nam",
        birthplace: "Hà Tĩnh",
        height: 178,
        weight: 72,
        bio: "Một tiền vệ năng động của đội.",
        season: "2024-2025",
        playerType: "Trong nước",
      },
      {
        id: 4,
        name: "Hoàng Đức",
        dob: "1998-01-11",
        position: "Tiền vệ",
        nationality: "Việt Nam",
        birthplace: "Hải Dương",
        height: 183,
        weight: 74,
        bio: "Tiền vệ xuất sắc của Viettel FC.",
        season: "2024-2025",
        playerType: "Trong nước",
      },
      {
        id: 6,
        name: "Geovane Magno",
        dob: "1994-03-02",
        position: "Tiền đạo",
        nationality: "Brazil",
        birthplace: "João Pessoa",
        height: 177,
        weight: 78,
        bio: "Tiền đạo ngoại binh chất lượng.",
        season: "2024-2025",
        playerType: "Nước ngoài",
      },
      {
        id: 12,
        name: "Jaha",
        dob: "1993-08-15",
        position: "Tiền vệ",
        nationality: "Uzbekistan",
        birthplace: "Tashkent",
        height: 180,
        weight: 76,
        bio: "Tiền vệ trung tâm mạnh mẽ.",
        season: "2024-2025",
        playerType: "Nước ngoài",
      },
    ],
    3: [
      {
        id: 7,
        name: "Hà Đức Chinh",
        dob: "1997-09-22",
        position: "Tiền đạo",
        nationality: "Việt Nam",
        birthplace: "Phú Thọ",
        height: 176,
        weight: 73,
        bio: "Tiền đạo chủ lực của SHB Đà Nẵng.",
        season: "2024-2025",
        playerType: "Trong nước",
      },
      {
        id: 8,
        name: "Nguyễn Phi Hoàng",
        dob: "2003-03-16",
        position: "Tiền vệ",
        nationality: "Việt Nam",
        birthplace: "Đà Nẵng",
        height: 170,
        weight: 65,
        bio: "Tài năng trẻ đầy triển vọng.",
        season: "2024-2025",
        playerType: "Trong nước",
      },
      {
        id: 13,
        name: "Lương Duy Cương",
        dob: "2001-11-07",
        position: "Hậu vệ",
        nationality: "Việt Nam",
        birthplace: "Đà Nẵng",
        height: 182,
        weight: 75,
        bio: "Trung vệ trẻ triển vọng.",
        season: "2024-2025",
        playerType: "Trong nước",
      },
    ],
    4: [
      {
        id: 9,
        name: "Nguyễn Tiến Linh",
        dob: "1997-10-20",
        position: "Tiền đạo",
        nationality: "Việt Nam",
        birthplace: "Hải Dương",
        height: 183,
        weight: 78,
        bio: "Tiền đạo ngôi sao của Becamex Bình Dương.",
        season: "2024-2025",
        playerType: "Trong nước",
      },
      {
        id: 10,
        name: "Victor Mansaray",
        dob: "1997-01-22",
        position: "Tiền đạo",
        nationality: "Sierra Leone",
        birthplace: "Freetown",
        height: 185,
        weight: 80,
        bio: "Tiền đạo ngoại binh mạnh mẽ.",
        season: "2024-2025",
        playerType: "Nước ngoài",
      },
      {
        id: 14,
        name: "Tống Anh Tỷ",
        dob: "1997-01-24",
        position: "Tiền vệ",
        nationality: "Việt Nam",
        birthplace: "Bình Định",
        height: 175,
        weight: 70,
        bio: "Tiền vệ trung tâm cần cù.",
        season: "2024-2025",
        playerType: "Trong nước",
      },
    ],
    5: [
      {
        id: 15,
        name: "Nguyễn Văn Toản",
        dob: "1999-11-26",
        position: "Thủ môn",
        nationality: "Việt Nam",
        birthplace: "Hải Phòng",
        height: 186,
        weight: 82,
        bio: "Thủ môn số một của Hải Phòng FC.",
        season: "2024-2025",
        playerType: "Trong nước",
      },
      {
        id: 16,
        name: "Joseph Mpande",
        dob: "1994-02-15",
        position: "Tiền đạo",
        nationality: "Ghana",
        birthplace: "Accra",
        height: 184,
        weight: 79,
        bio: "Tiền đạo ngoại binh nguy hiểm.",
        season: "2024-2025",
        playerType: "Nước ngoài",
      },
    ],
    6: [
      {
        id: 17,
        name: "Trần Nguyên Mạnh",
        dob: "1991-12-20",
        position: "Thủ môn",
        nationality: "Việt Nam",
        birthplace: "Nghệ An",
        height: 182,
        weight: 78,
        bio: "Thủ môn kỳ cựu của Nam Định FC.",
        season: "2024-2025",
        playerType: "Trong nước",
      },
      {
        id: 18,
        name: "Hendrio Araújo",
        dob: "1994-05-16",
        position: "Tiền vệ",
        nationality: "Brazil",
        birthplace: "São Paulo",
        height: 174,
        weight: 71,
        bio: "Tiền vệ kiến thiết tài hoa.",
        season: "2024-2025",
        playerType: "Nước ngoài",
      },
    ],
  },
};

// Khai báo availablePlayers - Danh sách cầu thủ có sẵn
const availablePlayers = [
  {
    id: 1,
    name: "Cầu thủ A1",
    dob: "1999-03-15",
    position: "Tiền đạo",
    nationality: "Việt Nam",
    birthplace: "Hà Nội",
    height: 180,
    weight: 75,
    bio: "Một tiền đạo tài năng của đội.",
    season: "2023-2024",
    playerType: "Trong nước",
  },
  {
    id: 2,
    name: "Văn Quyết",
    dob: "1991-07-01",
    position: "Tiền đạo",
    nationality: "Việt Nam",
    birthplace: "Hà Nội",
    height: 175,
    weight: 70,
    bio: "Đội trưởng tài ba của Hà Nội FC.",
    season: "2023-2024",
    playerType: "Trong nước",
  },
  {
    id: 3,
    name: "Cầu thủ B1",
    dob: "1998-05-20",
    position: "Tiền vệ",
    nationality: "Việt Nam",
    birthplace: "Hà Tĩnh",
    height: 178,
    weight: 72,
    bio: "Một tiền vệ năng động của đội.",
    season: "2023-2024",
    playerType: "Trong nước",
  },
  {
    id: 4,
    name: "Hoàng Đức",
    dob: "1998-01-11",
    position: "Tiền vệ",
    nationality: "Việt Nam",
    birthplace: "Hải Dương",
    height: 183,
    weight: 74,
    bio: "Tiền vệ xuất sắc của Viettel FC.",
    season: "2023-2024",
    playerType: "Trong nước",
  },
  {
    id: 5,
    name: "Đỗ Hùng Dũng",
    dob: "1993-09-08",
    position: "Tiền vệ",
    nationality: "Việt Nam",
    birthplace: "Hà Nội",
    height: 176,
    weight: 72,
    bio: "Tiền vệ trung tâm xuất sắc.",
    season: "2023-2024",
    playerType: "Trong nước",
  },
  {
    id: 6,
    name: "Geovane Magno",
    dob: "1994-03-02",
    position: "Tiền đạo",
    nationality: "Brazil",
    birthplace: "João Pessoa",
    height: 177,
    weight: 78,
    bio: "Tiền đạo ngoại binh chất lượng.",
    season: "2023-2024",
    playerType: "Nước ngoài",
  },
  {
    id: 7,
    name: "Hà Đức Chinh",
    dob: "1997-09-22",
    position: "Tiền đạo",
    nationality: "Việt Nam",
    birthplace: "Phú Thọ",
    height: 176,
    weight: 73,
    bio: "Tiền đạo chủ lực của SHB Đà Nẵng.",
    season: "2023-2024",
    playerType: "Trong nước",
  },
  {
    id: 8,
    name: "Nguyễn Phi Hoàng",
    dob: "2003-03-16",
    position: "Tiền vệ",
    nationality: "Việt Nam",
    birthplace: "Đà Nẵng",
    height: 170,
    weight: 65,
    bio: "Tài năng trẻ đầy triển vọng.",
    season: "2023-2024",
    playerType: "Trong nước",
  },
  {
    id: 9,
    name: "Nguyễn Tiến Linh",
    dob: "1997-10-20",
    position: "Tiền đạo",
    nationality: "Việt Nam",
    birthplace: "Hải Dương",
    height: 183,
    weight: 78,
    bio: "Tiền đạo ngôi sao của Becamex Bình Dương.",
    season: "2023-2024",
    playerType: "Trong nước",
  },
  {
    id: 10,
    name: "Victor Mansaray",
    dob: "1997-01-22",
    position: "Tiền đạo",
    nationality: "Sierra Leone",
    birthplace: "Freetown",
    height: 185,
    weight: 80,
    bio: "Tiền đạo ngoại binh mạnh mẽ.",
    season: "2023-2024",
    playerType: "Nước ngoài",
  },
  {
    id: 11,
    name: "Cầu thủ A2",
    dob: "2000-11-20",
    position: "Hậu vệ",
    nationality: "Việt Nam",
    birthplace: "Thái Bình",
    height: 179,
    weight: 74,
    bio: "Hậu vệ cánh đầy tốc độ.",
    season: "2024-2025",
    playerType: "Trong nước",
  },
  {
    id: 12,
    name: "Jaha",
    dob: "1993-08-15",
    position: "Tiền vệ",
    nationality: "Uzbekistan",
    birthplace: "Tashkent",
    height: 180,
    weight: 76,
    bio: "Tiền vệ trung tâm mạnh mẽ.",
    season: "2024-2025",
    playerType: "Nước ngoài",
  },
  {
    id: 13,
    name: "Lương Duy Cương",
    dob: "2001-11-07",
    position: "Hậu vệ",
    nationality: "Việt Nam",
    birthplace: "Đà Nẵng",
    height: 182,
    weight: 75,
    bio: "Trung vệ trẻ triển vọng.",
    season: "2024-2025",
    playerType: "Trong nước",
  },
  {
    id: 14,
    name: "Tống Anh Tỷ",
    dob: "1997-01-24",
    position: "Tiền vệ",
    nationality: "Việt Nam",
    birthplace: "Bình Định",
    height: 175,
    weight: 70,
    bio: "Tiền vệ trung tâm cần cù.",
    season: "2024-2025",
    playerType: "Trong nước",
  },
  {
    id: 15,
    name: "Nguyễn Văn Toản",
    dob: "1999-11-26",
    position: "Thủ môn",
    nationality: "Việt Nam",
    birthplace: "Hải Phòng",
    height: 186,
    weight: 82,
    bio: "Thủ môn số một của Hải Phòng FC.",
    season: "2024-2025",
    playerType: "Trong nước",
  },
  {
    id: 16,
    name: "Joseph Mpande",
    dob: "1994-02-15",
    position: "Tiền đạo",
    nationality: "Ghana",
    birthplace: "Accra",
    height: 184,
    weight: 79,
    bio: "Tiền đạo ngoại binh nguy hiểm.",
    season: "2024-2025",
    playerType: "Nước ngoài",
  },
  {
    id: 17,
    name: "Trần Nguyên Mạnh",
    dob: "1991-12-20",
    position: "Thủ môn",
    nationality: "Việt Nam",
    birthplace: "Nghệ An",
    height: 182,
    weight: 78,
    bio: "Thủ môn kỳ cựu của Nam Định FC.",
    season: "2024-2025",
    playerType: "Trong nước",
  },
  {
    id: 18,
    name: "Hendrio Araújo",
    dob: "1994-05-16",
    position: "Tiền vệ",
    nationality: "Brazil",
    birthplace: "São Paulo",
    height: 174,
    weight: 71,
    bio: "Tiền vệ kiến thiết tài hoa.",
    season: "2024-2025",
    playerType: "Nước ngoài",
  },
];
const stadiums = [
  {
    stadiumId: 1,
    stadiumName: "Hàng Đẫy",
    address: "Trịnh Hoài Đức, Cát Linh, Đống Đa, Hà Nội",
    capacity: 22500,
    standard: 5,
  },
  {
    stadiumId: 2,
    stadiumName: "Mỹ Đình",
    address: "Lê Đức Thọ, Mỹ Đình, Nam Từ Liêm, Hà Nội",
    capacity: 40192,
    standard: 5,
  },
  {
    stadiumId: 3,
    stadiumName: "Hòa Xuân",
    address: "Đường Khuê Mỹ, Hòa Hải, Ngũ Hành Sơn, Đà Nẵng",
    capacity: 20000,
    standard: 3,
  },
  {
    stadiumId: 4,
    stadiumName: "Gò Đậu",
    address: "48 Bạch Đằng, Phú Cường, Thủ Dầu Một, Bình Dương",
    capacity: 18250,
    standard: 4,
  },
  {
    stadiumId: 5,
    stadiumName: "Lạch Tray",
    address: "Lạch Tray, Ngô Quyền, Hải Phòng",
    capacity: 28000,
    standard: 4,
  },
  {
    stadiumId: 6,
    stadiumName: "Thiên Trường",
    address: "Trần Phú, Vị Hoàng, Nam Định",
    capacity: 20000,
    standard: 3,
  },
];

// New data structure for matches
const matchesData = [
  {
    matchId: 1,
    season: "2023-2024",
    round: "2023-2024-ROUND1",
    homeTeamId: 1,
    awayTeamId: 2,
    date: "2023-08-05",
    time: "19:15",
    homeScore: 2,
    awayScore: 1,
    stadiumId: 1,
    isFinished: true,
    goals: [
      { goalId: 1, time: "30'", teamId: 1, player: 2, type: "Penalty" },
      { goalId: 2, time: "75'", teamId: 2, player: 4, type: "normal" },
    ],
    cards: [
      { cardId: 1, player: 1, type: "Yellow", time: "60'", teamId: 1 },
    ],
  },
  {
    matchId: 2,
    season: "2023-2024",
    round: "2023-2024-ROUND2",
    homeTeamId: 2,
    awayTeamId: 1,
    date: "2024-01-02",
    time: "18:00",
    homeScore: 0,
    awayScore: 0,
    stadiumId: 1,
    isFinished: true,
    goals: [],
    cards: [],
  },
  {
    matchId: 3,
    season: "2023-2024",
    round: "2023-2024-ROUND1",
    homeTeamId: 3,
    awayTeamId: 4,
    date: "2023-08-06",
    time: "17:00",
    homeScore: 1,
    awayScore: 0,
    stadiumId: 3,
    isFinished: true,
    goals: [
      { goalId: 3, time: "45+1'", teamId: 3, player: 7, type: "normal" },
    ],
    cards: [
      { cardId: 2, player: 9, type: "Yellow", time: "25'", teamId: 4 },
    ],
  },
  {
    matchId: 4,
    season: "2023-2024",
    round: "2023-2024-ROUND2",
    homeTeamId: 4,
    awayTeamId: 3,
    date: "2024-01-03",
    time: "19:00",
    homeScore: 2,
    awayScore: 2,
    stadiumId: 4,
    isFinished: true,
    goals: [
      { goalId: 4, time: "15'", teamId: 4, player: 9, type: "normal" },
      { goalId: 5, time: "55'", teamId: 3, player: 8, type: "normal" },
      { goalId: 6, time: "80'", teamId: 4, player: 10, type: "normal" },
      { goalId: 7, time: "88'", teamId: 3, player: 7, type: "normal" },
    ],
    cards: [
      { cardId: 3, player: 8, type: "Yellow", time: "70'", teamId: 3 },
      { cardId: 4, player: 10, type: "Yellow", time: "78'", teamId: 4 },
    ],
  },
  {
    matchId: 5,
    season: "2024-2025",
    round: "2024-2025-ROUND1",
    homeTeamId: 1,
    awayTeamId: 3,
    date: "2024-09-05",
    time: "18:30",
    homeScore: 3,
    awayScore: 0,
    stadiumId: 1,
    isFinished: true,
    goals: [
      { goalId: 8, time: "10'", teamId: 1, player: 2, type: "normal" },
      { goalId: 9, time: "40'", teamId: 1, player: 5, type: "normal" },
      { goalId: 10, time: "65'", teamId: 1, player: 11, type: "normal" },
    ],
    cards: [],
  },
  {
    matchId: 6,
    season: "2024-2025",
    round: "2024-2025-ROUND1",
    homeTeamId: 2,
    awayTeamId: 4,
    date: "2024-09-06",
    time: "19:00",
    homeScore: 1,
    awayScore: 1,
    stadiumId: 1,
    isFinished: true,
    goals: [
      { goalId: 11, time: "22'", teamId: 2, player: 4, type: "normal" },
      { goalId: 12, time: "58'", teamId: 4, player: 9, type: "normal" },
    ],
    cards: [
      { cardId: 5, player: 3, type: "Yellow", time: "45'", teamId: 2 },
    ],
  },
  {
    matchId: 7,
    season: "2024-2025",
    round: "2024-2025-ROUND1",
    homeTeamId: 5,
    awayTeamId: 6,
    date: "2024-09-07",
    time: "17:30",
    homeScore: 2,
    awayScore: 0,
    stadiumId: 5,
    isFinished: true,
    goals: [
      { goalId: 13, time: "35'", teamId: 5, player: 15, type: "Penalty" },
      { goalId: 14, time: "82'", teamId: 5, player: 16, type: "normal" },
    ],
    cards: [],
  },
  {
    matchId: 8,
    season: "2024-2025",
    round: "2024-2025-ROUND2",
    homeTeamId: 3,
    awayTeamId: 1,
    date: "2025-02-15",
    time: "19:15",
    homeScore: 0,
    awayScore: 2,
    stadiumId: 3,
    isFinished: true,
    goals: [
      { goalId: 15, time: "50'", teamId: 1, player: 1, type: "normal" },
      { goalId: 16, time: "70'", teamId: 1, player: 2, type: "normal" },
    ],
    cards: [
      { cardId: 6, player: 7, type: "Yellow", time: "60'", teamId: 3 },
    ],
  },
  {
    matchId: 9,
    season: "2024-2025",
    round: "2024-2025-ROUND2",
    homeTeamId: 4,
    awayTeamId: 2,
    date: "2025-02-16",
    time: "18:00",
    homeScore: 1,
    awayScore: 0,
    stadiumId: 4,
    isFinished: true,
    goals: [
      { goalId: 17, time: "85'", teamId: 4, player: 9, type: "normal" },
    ],
    cards: [],
  },
  {
    matchId: 10,
    season: "2024-2025",
    round: "2024-2025-ROUND2",
    homeTeamId: 6,
    awayTeamId: 5,
    date: "2025-02-17",
    time: "19:30",
    homeScore: 1,
    awayScore: 1,
    stadiumId: 6,
    isFinished: true,
    goals: [
      { goalId: 18, time: "12'", teamId: 6, player: 17, type: "Penalty" },
      { goalId: 19, time: "78'", teamId: 5, player: 15, type: "normal" },
    ],
    cards: [
      { cardId: 7, player: 16, type: "Yellow", time: "40'", teamId: 5 },
    ],
  },
];
let typeSettings = {
  goalTypes: [
    { code: "BT001", name: "Bàn thắng thường", description: "Bàn thắng được ghi trong tình huống thông thường." },
    { code: "BT002", name: "Phản lưới nhà", description: "Bàn thắng do cầu thủ tự đưa bóng vào lưới nhà." },
    { code: "BT003", name: "Penalty", description: "Bàn thắng từ chấm phạt đền." },
    { code: "BT004", name: "Đánh đầu", description: "Bàn thắng được ghi bằng đầu." },
    { code: "BT005", name: "Sút xa", description: "Bàn thắng được ghi từ ngoài vòng cấm." },
    { code: "BT006", name: "Sút phạt", description: "Bàn thắng được ghi từ tình huống đá phạt trực tiếp." },
  ],
  cardTypes: [
    { code: "TP001", name: "Vàng", description: "Cảnh cáo cho hành vi phi thể thao." },
    { code: "TP002", name: "Đỏ", description: "Truất quyền thi đấu do lỗi nghiêm trọng." },
    { code: "TP003", name: "Vàng thứ hai (thành đỏ)", description: "Cầu thủ nhận thẻ đỏ sau khi đã có một thẻ vàng." },
  ],
  priorityOptions: [
    { code: "UT1", name: "Điểm số" },
    { code: "UT2", name: "Hiệu số bàn thắng bại" },
    { code: "UT3", name: "Tổng số bàn thắng ghi được" },
    { code: "UT4", name: "Số bàn thắng trên sân khách" },
    { code: "UT5", name: "Đối đầu trực tiếp" },
  ],
  rankingPriorityOrder: ["UT1", "UT2", "UT3", "UT4", "UT5"],
};

let settingsData = {
  minPlayers: 18,
  maxPlayers: 25,
  maxForeignPlayers: 4,
  minAge: 17,
  maxAge: 38,
  minCapacity: 15000,
  minStar: 3,
  participationFee: 1500000000,
  transferWindowOpen: true,
  transferWindowStart: "2024-06-15",
  transferWindowEnd: "2024-07-15",
  winPoints: 3,
  drawPoints: 1,
  losePoints: 0,
  maxGoalTime: 90,
  injuryTimeLimit: 7,
};

let teamsPosition = {
  1: [
    {
      season: "2022-2023",
      win: 15,
      loss: 5,
      draw: 6,
      difference: 25,
      point: 51,
      posiotion: 2,
    },
    {
      season: "2023-2024",
      win: 10,
      loss: 6,
      draw: 4,
      point: 34,
      difference: 12,
      posiotion: 3,
    },
    {
      season: "2024-2025",
      win: 12,
      loss: 4,
      draw: 2,
      point: 38,
      difference: 18,
      posiotion: 1,
    },
  ],
  2: [
    {
      season: "2022-2023",
      win: 18,
      loss: 3,
      draw: 5,
      difference: 30,
      point: 59,
      posiotion: 1,
    },
    {
      season: "2023-2024",
      win: 8,
      loss: 8,
      draw: 4,
      point: 28,
      difference: -5,
      posiotion: 5,
    },
    {
      season: "2024-2025",
      win: 9,
      loss: 5,
      draw: 4,
      point: 31,
      difference: 5,
      posiotion: 4,
    },
  ],
  3: [
    {
      season: "2023-2024",
      win: 7,
      loss: 7,
      draw: 6,
      point: 27,
      difference: -2,
      posiotion: 6,
    },
    {
      season: "2024-2025",
      win: 6,
      loss: 8,
      draw: 4,
      point: 22,
      difference: -8,
      posiotion: 7,
    },
  ],
  4: [
    {
      season: "2023-2024",
      win: 9,
      loss: 5,
      draw: 6,
      point: 33,
      difference: 8,
      posiotion: 4,
    },
    {
      season: "2024-2025",
      win: 10,
      loss: 6,
      draw: 2,
      point: 32,
      difference: 7,
      posiotion: 3,
    },
  ],
  5: [
    {
      season: "2024-2025",
      win: 11,
      loss: 3,
      draw: 4,
      point: 37,
      difference: 15,
      posiotion: 2,
    },
  ],
  6: [
    {
      season: "2024-2025",
      win: 5,
      loss: 10,
      draw: 3,
      point: 18,
      difference: -15,
      posiotion: 8,
    },
  ],
};
module.exports = {
  availableTeams,
  seasons,
  players,
  availablePlayers,
  stadiums,
  matchesData,
  typeSettings,
  settingsData,
  teamsPosition
  };