const availableTeams = [
  {
    id: 1,
    name: "Hà Nội FC",
    city: "Hà Nội",
    coach: "Gad",
    stadium: "Hàng Đẫy",
    stadiumId: 1,
    capacity: 22500,
    standard: 5,
    home_kit_image: "https://upload.wikimedia.org/wikipedia/vi/e/eb/Hanoi_FC.png",
    away_kit_image: null,
    third_kit_image: null,
    description: "Câu lạc bộ bóng đá Hà Nội",
    season: null,
  },
  {
    id: 2,
    name: "Viettel FC",
    city: "Hà Nội",
    coach: "Tăng Nhất",
    stadium: "Hàng Đẫy",
    stadiumId: 1,
    capacity: 22500,
    standard: 4,
    home_kit_image: null,
    away_kit_image:
      "https://upload.wikimedia.org/wikipedia/vi/thumb/d/d5/Viettel_FC_logo.png/1200px-Viettel_FC_logo.png",
    third_kit_image: null,
    description: "Câu lạc bộ bóng đá Viettel",
    season: null,
  },
];

const seasons = [
  {
    id: "2023-2024",
    name: "Mùa giải 2023-2024",
    startDate: "2023-08-01",
    endDate: "2024-05-30",
    teams: [1, 2],
    rounds: [
      {
        roundId: "2023-2024-ROUND1",
        name: "Lượt đi",
        startDate: "2023-08-05",
        endDate: "2023-08-07",
      },
      {
        roundId: "2023-2024-ROUND2",
        name: "Lượt về",
        startDate: "2024-01-01",
        endDate: "2024-01-03",
      },
    ],
  },
];

const players = {
  "2023-2024": {
    1: [
      {
        id: 1,
        name: "Cầu thủ A1",
        dob: "1999-03-15",
        position: "Tiền đạo",
        nationality: "Việt Nam",
        birthplace: "Hà Nội",
        height: 180,
        weight: 75,
        bio: "Một tiền đạo tài năng của đội.",
        season: "2023-2024",
        playerType: "Trong nước",
      },
      {
        id: 2,
        name: "Văn Quyết",
        dob: "1991-07-01",
        position: "Tiền đạo",
        nationality: "Việt Nam",
        birthplace: "Hà Nội",
        height: 175,
        weight: 70,
        bio: "Đội trưởng tài ba của Hà Nội FC.",
        season: "2023-2024",
        playerType: "Trong nước",
      },
    ],
    2: [
      {
        id: 3,
        name: "Cầu thủ B1",
        dob: "1998-05-20",
        position: "Tiền vệ",
        nationality: "Việt Nam",
        birthplace: "Hà Tĩnh",
        height: 178,
        weight: 72,
        bio: "Một tiền vệ năng động của đội.",
        season: "2023-2024",
        playerType: "Trong nước",
      },
      {
        id: 4,
        name: "Hoàng Đức",
        dob: "1998-01-11",
        position: "Tiền vệ",
        nationality: "Việt Nam",
        birthplace: "Hải Dương",
        height: 183,
        weight: 74,
        bio: "Tiền vệ xuất sắc của Viettel FC.",
        season: "2023-2024",
        playerType: "Trong nước",
      },
    ],
  },
};

// Khai báo availablePlayers - Danh sách cầu thủ có sẵn
const availablePlayers = [
  {
    id: 1,
    name: "Cầu thủ A1",
    dob: "1999-03-15",
    position: "Tiền đạo",
    nationality: "Việt Nam",
    birthplace: "Hà Nội",
    height: 180,
    weight: 75,
    bio: "Một tiền đạo tài năng của đội.",
    season: "2023-2024",
    playerType: "Trong nước",
  },
  {
    id: 2,
    name: "Văn Quyết",
    dob: "1991-07-01",
    position: "Tiền đạo",
    nationality: "Việt Nam",
    birthplace: "Hà Nội",
    height: 175,
    weight: 70,
    bio: "Đội trưởng tài ba của Hà Nội FC.",
    season: "2023-2024",
    playerType: "Trong nước",
  },
  {
    id: 3,
    name: "Cầu thủ B1",
    dob: "1998-05-20",
    position: "Tiền vệ",
    nationality: "Việt Nam",
    birthplace: "Hà Tĩnh",
    height: 178,
    weight: 72,
    bio: "Một tiền vệ năng động của đội.",
    season: "2023-2024",
    playerType: "Trong nước",
  },
  {
    id: 4,
    name: "Hoàng Đức",
    dob: "1998-01-11",
    position: "Tiền vệ",
    nationality: "Việt Nam",
    birthplace: "Hải Dương",
    height: 183,
    weight: 74,
    bio: "Tiền vệ xuất sắc của Viettel FC.",
    season: "2023-2024",
    playerType: "Trong nước",
  },
];
const stadiums = [
  {
    stadiumId: 1,
    stadiumName: "Hàng Đẫy",
    address: "Trịnh Hoài Đức, Cát Linh, Đống Đa, Hà Nội",
    capacity: 22500,
    standard: 5,
  },
  {
    stadiumId: 2,
    stadiumName: "Mỹ Đình",
    address: "Lê Đức Thọ, Mỹ Đình, Nam Từ Liêm, Hà Nội",
    capacity: 40192,
    standard: 5,
  },
];

// New data structure for matches
const matchesData = [
  {
    matchId: 1,
    season: "2023-2024",
    round: "2023-2024-ROUND1",
    homeTeamId: 1,
    awayTeamId: 2,
    date: "2023-08-05",
    time: "19:15",
    homeScore: 2,
    awayScore: 1,
    stadiumId: 1,
    isFinished: true,
    goals: [
      { goalId: 1, time: "30'", teamId: 1, player: 2, type: "Penalty" },
      { goalId: 2, time: "75'", teamId: 2, player: 4, type: "normal" },
    ],
    cards: [
      { cardId: 1, player: 1, type: "Yellow", time: "60'", teamId: 1 },
    ],
  },
  {
    matchId: 2,
    season: "2023-2024",
    round: "2023-2024-ROUND2",
    homeTeamId: 2,
    awayTeamId: 1,
    date: "2024-01-02",
    time: "18:00",
    homeScore: 0,
    awayScore: 0,
    stadiumId: 1,
    isFinished: true,
    goals: [],
    cards: [],
  },
];
let typeSettings = {
  goalTypes: [
    { code: "BT001", name: "Bàn thắng thường", description: "Bàn thắng được ghi trong tình huống thông thường." },
    { code: "BT002", name: "Phản lưới nhà", description: "Bàn thắng do cầu thủ tự đưa bóng vào lưới nhà." },
    { code: "BT003", name: "Penalty", description: "Bàn thắng từ chấm phạt đền." },
  ],
  cardTypes: [
    { code: "TP001", name: "Vàng", description: "Cảnh cáo cho hành vi phi thể thao." },
    { code: "TP002", name: "Đỏ", description: "Truất quyền thi đấu do lỗi nghiêm trọng." },
  ],
  priorityOptions: [
    { code: "UT1", name: "Điểm số" },
    { code: "UT2", name: "Hiệu số" },
    { code: "UT3", name: "Số bàn thắng" },
  ],
  rankingPriorityOrder: ["UT1", "UT2", "UT3"],
};
let settingsData = {
  minPlayers: 15,
  maxPlayers: 22,
  maxForeignPlayers: 3,
  minAge: 16,
  maxAge: 40,
  minCapacity: 10000,
  minStar: 2,
  participationFee: 1000000000,
  winPoints: 3,
  drawPoints: 1,
  losePoints: 0,
  maxGoalTime: 90,
};
let teamsPosition = {
  1: [
    {
      season: "2022-2023",
      win: 2,
      loss: 0,
      draw: 0,
      difference: 2,
      point: 6,
      posiotion: 1,
    },
    {
      season: "2023-2024",
      win: 1,
      loss: 1,
      draw: 0,
      point: 3,
      difference: 1,
      posiotion: 2,
    },
  ],
  2: [
    {
      season: "2022-2023",
      win: 1,
      loss: 1,
      draw: 0,
      difference: 1,
      point: 3,
      posiotion: 2,
    },
    {
      season: "2023-2024",
      win: 0,
      loss: 1,
      draw: 1,
      point: 1,
      difference: -2,
      posiotion: 3,
    },
  ],
  3: [
    {
      season: "2022-2023",
      win: 0,
      loss: 2,
      draw: 0,
      difference: -3,
      point: 0,
      posiotion: 3,
    },
    {
      season: "2023-2024",
      win: 1,
      loss: 0,
      draw: 1,
      point: 4,
      difference: 1,
      posiotion: 1,
    },
  ],
};
let playerCards = {
  "2022-2023": [
    {
      id: 1,
      name: "Cầu thủ A1",
      teamId: 1,
      team: "Team A",
      playerType: "Trong nước",
      soThe: 3,
      playerState: false,
    },
    {
      id: 2,
      name: "Cầu thủ B2",
      teamId: 2,
      team: "Team B",
      playerType: "Trong nước",
      soThe: 1,
      playerState: true,
    },
    {
      id: 3,
      name: "Cầu thủ C3",
      teamId: 3,
      team: "Team C",
      playerType: "Trong nước",
      soThe: 2,
      playerState: false,
    }
  ],
  "2024-2025": [],
};
module.exports = {
  availableTeams,
  seasons,
  players,
  availablePlayers,
  stadiums,
  matchesData,
  typeSettings,
  settingsData,
  teamsPosition,
  playerCards
};