services:
  server:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app 
    environment:
      - DEBUG=True  
      - ALLOWED_HOSTS=*
    entrypoint: ["sh", "/entrypoint.sh"]
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]