# Generated by Django 5.1.7 on 2025-03-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FastaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="fasta_files/")),
                (
                    "model_choice",
                    models.CharField(
                        choices=[
                            ("kmeans", "K-Means Clustering"),
                            ("hierarchical", "Hierarchical Clustering"),
                        ],
                        default="kmeans",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
