# Generated by Django 5.1.7 on 2025-03-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusterapp', '0002_fastafile_linkage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastafile',
            name='linkage',
            field=models.CharField(blank=True, choices=[('single', 'Single Linkage'), ('complete', 'Complete Linkage'), ('average', 'Average Linkage'), ('centroid', 'Centroid Linkage')], default='ward', max_length=20, null=True),
        ),
    ]
