CREATE DATABASE QUANLIDEAN
USE QUANLIDEAN
CREATE TABLE NHANVIEN (
	HONV nvarchar(15),
	TENLOT nvarchar(15),
	TENNV nvarchar(15),
	MANV nvarchar(9),
	NGSINH date,
	DCHI nvarchar(30),
	PHAI nvarchar(3),
	LUONG float,
	MA_NQL nvarchar(9),
	PHG int
	PRIMARY KEY (MANV)
)

CREATE TABLE PHONGBAN (
	TENPHG nvarchar(15),
	MAPHG int,
	TRPHG nvarchar(9),
	NG_NHANCHUC date
	PRIMARY KEY (MAPHG)
)

CREATE TABLE DIADIEM_PHG (
	MAPHG int,
	DIADIEM	nvarchar(15)
	PRIMARY KEY (MAPHG, DIADIEM)
)

CREATE TABLE DEAN (
	TENDA nvarchar(15),
	MADA int,
	DDIEM_DA nvarchar(15),
	PHONG int
	PRIMARY KEY (MADA)
)

CREATE TABLE CONGVIEC (
	MADA int,
	STT int,
	TEN_CONG_VIEC nvarchar(50)
	PRIMARY KEY (MADA, STT)
)

CREATE TABLE PHANCONG (
	MA_NVIEN nvarchar(9),
	MADA int,
	STT int,
	THOIGIAN float
	PRIMARY KEY (MA_NVIEN, MADA)
)

CREATE TABLE THANNHAN (
	MA_NVIEN nvarchar(9),
	TENTN nvarchar(15),
	PHAI nvarchar(3),
	NGSINH datetime,
	QUANHE nvarchar(15)
	PRIMARY KEY (MA_NVIEN, TENTN)
)

SET DATEFORMAT DMY;

INSERT INTO NHANVIEN VALUES (N'Đinh', N'Bá', N'Tiên', '009', '11/02/1960', N'119 Cống Quỳnh, Tp HCM', 'Nam', 30000, '005', 5)
INSERT INTO NHANVIEN VALUES (N'Nguyễn', N'Thanh', N'Tùng', '005', '20/08/1962', N'222 Nguyễn Văn Cừ, Tp HCM', 'Nam', 40000, '006', 5)
INSERT INTO NHANVIEN VALUES (N'Bùi', N'Ngọc', N'Hằng', '007', '11/3/1954', N'332 Nguyễn Thái Học, Tp HCM', 'Nam', 25000, '001', 4)
INSERT INTO NHANVIEN VALUES (N'Lê', N'Quỳnh', N'Như', '001', '01/02/1967', N'291 Hồ Văn Huê, Tp HCM', N'Nữ', 43000, '006', 4)
INSERT INTO NHANVIEN VALUES (N'Nguyễn', N'Mạnh', N'Hùng', '004', '04/03/1967', N'95 Bà Rịa, Vũng Tàu', 'Nam', 38000, '005', 5)
INSERT INTO NHANVIEN VALUES (N'Trần', N'Thanh', N'Tâm', '003', '04/05/1957', N'34 Mai Thị Lự, Tp HCM', 'Nam', 25000, '005', 5)
INSERT INTO NHANVIEN VALUES (N'Trần', N'Hồng', N'Quang', '008', '01/09/1967', N'80 Lê Hồng Phong, Tp HCM', 'Nam', 25000, '001', 4)
INSERT INTO NHANVIEN VALUES (N'Phạm', N'Văn', N'Vinh', '006', '01/01/1965', N'45 Trưng Vương, Hà Nội', N'Nữ', 55000, NULL, 1)

INSERT INTO PHONGBAN VALUES(N'Nghiên cứu', 5, '005', '22/05/1978')
INSERT INTO PHONGBAN VALUES(N'Điều hành', 4, '008', '01/01/1985')
INSERT INTO PHONGBAN VALUES(N'Quản lý', 1, '006', '19/06/1971')

SET DATEFORMAT DMY
INSERT INTO THANNHAN VALUES('005', N'Trinh', N'Nữ', '05/04/1976', N'Con gái')
INSERT INTO THANNHAN VALUES('005', N'Khang', N'Nam', '25/10/1973', N'Con trai')
INSERT INTO THANNHAN VALUES('005', N'Phương', N'Nữ', '03/05/1948', N'Vợ chồng')
INSERT INTO THANNHAN VALUES('001', N'Minh', N'Nam', '29/02/1932', N'Vợ chồng')
INSERT INTO THANNHAN VALUES('009', N'Tiến', N'Nam', '01/01/1978', N'Con trai')
INSERT INTO THANNHAN VALUES('009', N'Châu', N'Nữ', '30/12/1978', N'Con gái')
INSERT INTO THANNHAN VALUES('009', N'Phương', N'Nữ', '05/05/1957', N'Vợ chồng')

INSERT INTO	DEAN VALUES('San pham X', 1, N'Vũng Tàu', 5)
INSERT INTO	DEAN VALUES('San pham Y', 2, N'Nha Trang', 5)
INSERT INTO	DEAN VALUES('San pham Z', 3, N'TP HCM', 5)
INSERT INTO	DEAN VALUES('Tin hoa hoc', 10, N'Hà Nội', 4)
INSERT INTO	DEAN VALUES('Cap quang', 20, N'TP HCM', 1)
INSERT INTO	DEAN VALUES('Dao tao', 30, N'Hà Nội', 4)

INSERT INTO DIADIEM_PHG VALUES(1, 'TP HCM')
INSERT INTO DIADIEM_PHG VALUES(4, 'Hà Nội')
INSERT INTO DIADIEM_PHG VALUES(5, 'TAU')
INSERT INTO DIADIEM_PHG VALUES(5, 'NHA TRANG')
INSERT INTO DIADIEM_PHG VALUES(5, 'TP HCM')

INSERT INTO PHANCONG VALUES('009', 1, 1, 32)
INSERT INTO PHANCONG VALUES('009', 2, 2, 8)
INSERT INTO PHANCONG VALUES('004', 3, 1, 40)
INSERT INTO PHANCONG VALUES('003', 1, 2, 20.0)
INSERT INTO PHANCONG VALUES('003', 2, 1, 20.0)
INSERT INTO PHANCONG VALUES('008', 10, 1, 35)
INSERT INTO PHANCONG VALUES('008', 30, 2, 5)
INSERT INTO PHANCONG VALUES('001', 30, 1, 20)
INSERT INTO PHANCONG VALUES('001', 20, 1, 15)
INSERT INTO PHANCONG VALUES('006', 20, 1, 30)
INSERT INTO PHANCONG VALUES('005', 3, 1, 10)
INSERT INTO PHANCONG VALUES('005', 10, 2, 10)
INSERT INTO PHANCONG VALUES('005', 20, 1, 10)
INSERT INTO PHANCONG VALUES('007', 30, 2, 30)
INSERT INTO PHANCONG VALUES('007', 10, 2, 10)

INSERT INTO CONGVIEC VALUES(1, 1, 'Thiet ke san pham X')
INSERT INTO CONGVIEC VALUES(1, 2, 'Thu nghiem san pham X')
INSERT INTO CONGVIEC VALUES(2, 1, 'San xuat san pham Y')
INSERT INTO CONGVIEC VALUES(2, 2, 'Quang cao san pham Y')
INSERT INTO CONGVIEC VALUES(3, 1, 'Khuyen mai san pham Z')
INSERT INTO CONGVIEC VALUES(10, 1, 'Tin hoc hoa nhan su tien luong')
INSERT INTO CONGVIEC VALUES(10, 2, 'Tin hoc hoa phong Kinh doanh')
INSERT INTO CONGVIEC VALUES(20, 1, 'Lap dat cap quang')
INSERT INTO CONGVIEC VALUES(30, 1, 'Dao tao nhan vien Marketing')
INSERT INTO CONGVIEC VALUES(30, 2, 'Dao tao chuyen vien vien thiet ke')
GO
--1. Số lượng nhân viên của mỗi bộ phận tối đa là 7 người.
---			INSERT	DELETE	UPDATE
---NHANVIEN   +        -       +(PHG)
CREATE TRIGGER slnv ON NHANVIEN
FOR INSERT, UPDATE
AS 
BEGIN
	IF (SELECT COUNT(*)
		FROM INSERTED INS JOIN PHONGBAN PB ON INS.PHG = PB.MAPHG
						  JOIN NHANVIEN NV ON NV.PHG = PB.MAPHG
		GROUP BY PB.MAPHG) > 8 
	BEGIN
		PRINT 'LOI: SO LUONG NHAN VIEN KHONG HOP LE'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'THEM/SUA THANH CONG'
	END
END
GO
	
--2. Lương của quản lý không được nhỏ hơn 25000
---			INSERT	DELETE	UPDATE
---NHANVIEN    +	  -		  +(LUONG)
CREATE TRIGGER luongnql ON NHANVIEN
FOR INSERT, UPDATE
AS 
BEGIN
	IF (SELECT LUONG
		FROM INSERTED
		WHERE MANV IN (
						SELECT MA_NQL
						FROM NHANVIEN
						)) < 25000
	BEGIN
		PRINT 'LOI: LUONG KHONG HOP LE'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'THEM/SUA THANH CONG'
	END
END
GO
--3. Một nhân viên chỉ được làm tối đa 3 dự án.
---			INSERT	DELETE	UPDATE
---PHANCONG    +	  -		  +(MADA)
CREATE TRIGGER slda ON PHANCONG
FOR INSERT, UPDATE
AS
BEGIN
	IF (SELECT COUNT(*)
		FROM PHANCONG
		GROUP BY MA_NVIEN
		) > 3
	BEGIN
		PRINT 'LOI: NHAN VIEN DUOC PHAN CONG TREN 3 DE AN'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'THEM/SUA THANH CONG'
	END
END
GO
--4. Ngày nhận chức của quản lý phải sau ngày sinh nhật của người đó.
---			INSERT	DELETE	UPDATE
---NHANVIEN    +	  -		  +(NGSINH, PHG)
---PHONGBAN    +	  -		  +(TRGPHG, NG_NHANCHUC)
CREATE TRIGGER ngnhanchuc_ngsinh_NV ON NHANVIEN
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS(SELECT * 
			  FROM INSERTED INS JOIN PHONGBAN PB ON INS.MANV = PB.TRPHG
			  WHERE NGSINH > NG_NHANCHUC
			  )
	BEGIN
		PRINT 'LOI: NGAY SINH - NGAY NHAN CHUC KHONG HOP LE'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'THEM/SUA THANH CONG'
	END
END
GO

CREATE TRIGGER ngnhanchuc_ngsinh_PB ON PHONGBAN
FOR INSERT, UPDATE
AS 
BEGIN
	IF EXISTS(SELECT *
			  FROM INSERTED INS JOIN NHANVIEN NV ON INS.TRPHG = NV.MANV
			  WHERE NGSINH > NG_NHANCHUC
			  )
	BEGIN
		PRINT 'LOI: NGAY SINH - NGAY NHAN CHUC KHONG HOP LE'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'THEM/SUA THANH CONG'
	END
END
GO
--5. Lương của nhân viên phải không được cao hơn lương của người quản lý trực tiếp của mình.
---			INSERT	DELETE	UPDATE
---NHANVIEN    +	  -		  +(LUONG, MA_NQL)
CREATE TRIGGER luongnv_luongnql ON NHANVIEN
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS (SELECT *
			   FROM INSERTED 
			   WHERE INSERTED.LUONG > (SELECT LUONG 
									   FROM NHANVIEN NV JOIN INSERTED INS ON NV.MANV = INS.MA_NQL
									   )
			  )
	BEGIN
		PRINT 'LOI: LUONG NHAN VIEN - LUONG NQL KHONG HOP LE'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'THEM/SUA THANH CONG'
	END
END
GO
--6. Không được phân công thêm đề án cho nhân viên đang làm từ 02 đề án trở lên.
---			INSERT	DELETE	UPDATE
---PHANCONG    +	  -		  -
CREATE TRIGGER phancongdean ON PHANCONG
FOR INSERT
AS
BEGIN
	IF EXISTS (SELECT * 
			   FROM INSERTED I JOIN
									(SELECT MA_NVIEN, COUNT(*) AS SL
									FROM PHANCONG 
									GROUP BY MA_NVIEN) AS TMP ON I.MA_NVIEN = TMP.MA_NVIEN
			   WHERE SL >= 3
			   )
	BEGIN
		PRINT 'LOI: PHAN CONG KHONG HOP LE'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'THEM/SUA THANH CONG'
	END
END
GO

--7. Lương của trưởng phòng phải lớn hơn của tất cả nhân viên của phòng đó.
---			INSERT	DELETE	UPDATE
---NHANVIEN   +		  -		  +(LUONG)
---PHONGBAN   -		  -		  +(TRGPHG)
CREATE TRIGGER luongtrgphg_NV ON NHANVIEN
FOR INSERT, UPDATE
AS
BEGIN
	 IF EXISTS (SELECT *
				FROM INSERTED I JOIN PHONGBAN PB ON I.PHG = PB.MAPHG 
				WHERE I.LUONG > (SELECT LUONG 
								 FROM NHANVIEN NV
								 WHERE NV.MANV = PB.TRPHG)
				)
	BEGIN
		PRINT 'LOI: LUONG KHONG HOP LE'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'THEM/SUA THANH CONG'
	END
END
GO

CREATE TRIGGER luongtrgphg_PB ON PHONGBAN
FOR UPDATE
AS
BEGIN
	 IF EXISTS (SELECT *	
		FROM INSERTED I JOIN NHANVIEN NV ON I.TRPHG = NV.MANV
		WHERE LUONG < ANY (SELECT LUONG
						   FROM NHANVIEN NV
						   WHERE NV.PHG = I.MAPHG)
				)
	BEGIN
		PRINT 'LOI: LUONG KHONG HOP LE'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'THEM/SUA THANH CONG'
	END
END
GO

